version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app


  db:
    image: postgres:latest
    # Only for testing
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data

    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]


  # test:
  #   image: osexp2000/ubuntu-with-utils
  #   command: "/bin/bash"
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   expose:
  #     - "80"
